import { useState, useEffect } from 'react';
import { LETTER_SCHEMAS } from '../utils/letterSchemas';

// Render Kop Desa Cemara
function renderHeader() {
  return `
    <div style="text-align: center; margin-bottom: 30px; border-bottom: 3px solid #1d4ed8; padding-bottom: 20px;">
      <h1 style="margin: 0; font-size: 24px; font-weight: bold; color: #1d4ed8;">PEMERINTAH KABUPATEN...</h1>
      <h2 style="margin: 5px 0 0 0; font-size: 20px; font-weight: bold;">KECAMATAN...</h2>
      <h3 style="margin: 5px 0 0 0; font-size: 18px; font-weight: bold;">DESA CEMARA</h3>
      <p style="margin: 5px 0 0 0; font-size: 14px; color: #666;">Jl. ... No. ... Telp. ... Kode Pos ...</p>
    </div>
  `;
}

// Render info pengajuan
function renderSubmissionInfo(submission) {
  const jenisLabel = submission.jenis_surat in LETTER_SCHEMAS 
    ? LETTER_SCHEMAS[submission.jenis_surat].label 
    : submission.jenis_surat;
  
  const statusColor = {
    'Menunggu': '#f59e0b',
    'Disetujui': '#10b981',
    'Ditolak': '#ef4444'
  }[submission.status] || '#6b7280';

  let html = `
    <div style="background: #f9fafb; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
      <h4 style="margin: 0 0 10px 0; font-size: 14px; font-weight: bold; color: #374151;">INFORMASI PENGAJUAN</h4>
      <table style="width: 100%; font-size: 13px;">
        <tr>
          <td style="width: 150px; vertical-align: top; padding: 2px 0;">No. Referensi</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0; font-family: monospace;">${submission.nomor_referensi}</td>
        </tr>
        <tr>
          <td style="padding: 2px 0;">Jenis Surat</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0;">${jenisLabel}</td>
        </tr>
        <tr>
          <td style="padding: 2px 0;">Tanggal</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0;">${new Date(submission.tanggal_pengajuan).toLocaleDateString('id-ID', { 
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
          })}</td>
        </tr>
        <tr>
          <td style="padding: 2px 0;">Status</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0;">
            <span style="display: inline-block; padding: 2px 8px; background: ${statusColor}; color: white; border-radius: 4px; font-size: 12px;">
              ${submission.status}
            </span>
          </td>
        </tr>
  `;

  if (submission.nomor_surat) {
    html += `
        <tr>
          <td style="padding: 2px 0;">Nomor Surat</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0; font-family: monospace;">${submission.nomor_surat}</td>
        </tr>
    `;
  }

  if (submission.alasan_penolakan) {
    html += `
        <tr>
          <td style="padding: 2px 0; vertical-align: top;">Alasan Penolakan</td>
          <td style="padding: 2px 0; vertical-align: top;">:</td>
          <td style="padding: 2px 0; color: #dc2626;">${submission.alasan_penolakan}</td>
        </tr>
    `;
  }

  html += `
      </table>
    </div>
  `;
  return html;
}

// Render data pemohon
function renderApplicantData(submission) {
  return `
    <div style="background: #eff6ff; padding: 15px; border-radius: 8px; margin-bottom: 20px; border-left: 4px solid #3b82f6;">
      <h4 style="margin: 0 0 10px 0; font-size: 14px; font-weight: bold; color: #1e40af;">DATA PEMOHON</h4>
      <table style="width: 100%; font-size: 13px;">
        <tr>
          <td style="width: 150px; padding: 2px 0;">Nama</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0;">${submission.nama_lengkap}</td>
        </tr>
        <tr>
          <td style="padding: 2px 0;">NIK</td>
          <td style="padding: 2px 0;">:</td>
          <td style="padding: 2px 0;">${submission.nik}</td>
        </tr>
      </table>
    </div>
  `;
}

// Render footer disclaimer
function renderFooter() {
  return `
    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #d1d5db; text-align: center; font-size: 12px; color: #6b7280;">
      <p>Generated by Desa Cemara Smart Letter Service</p>
      <p style="margin-top: 5px;">Invoice ini merupakan bukti pengajuan surat yang sah.</p>
    </div>
  `;
}

// Main render function
export function renderInvoiceHTML(submission) {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Invoice - ${submission.nomor_referensi}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
          padding: 40px 60px;
          background: white;
          color: #1f2937;
        }
        .invoice {
          max-width: 595px;
          margin: 0 auto;
          background: white;
          min-height: 842px;
        }
        h1, h2, h3, h4 {
          color: #1f2937;
        }
        table {
          border-collapse: collapse;
        }
        @media print {
          @page {
            size: A5;
            margin: 15mm;
          }
          body {
            padding: 0;
          }
        }
      </style>
    </head>
    <body>
      <div class="invoice">
        ${renderHeader()}
        ${renderSubmissionInfo(submission)}
        ${renderApplicantData(submission)}
        <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
        ${renderFooter()}
      </div>
    </body>
    </html>
  `;
}

// InvoiceView Component
export default function InvoiceView({ submission, onClose }) {
  const [showPrint, setShowPrint] = useState(false);

  const handlePrint = () => {
    setShowPrint(true);
  };

  const handleAfterPrint = () => {
    setShowPrint(false);
    if (onClose) onClose();
  };

  // Inject print styles
  if (typeof document !== 'undefined') {
    if (!document.getElementById('invoice-print-styles')) {
      const styleEl = document.createElement('style');
      styleEl.id = 'invoice-print-styles';
      styleEl.textContent = `
        @media print {
          body * {
            visibility: hidden;
          }
          #invoice-frame, #invoice-frame * {
            visibility: visible;
          }
          #invoice-frame {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            border: none;
            margin: 0;
            padding: 0;
          }
        }
      `;
      document.head.appendChild(styleEl);
    }
  }

  const invoiceHTML = renderInvoiceHTML(submission);

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b flex items-center justify-between bg-gray-50">
          <div>
            <h3 className="text-lg font-semibold text-gray-900">Invoice Pengajuan</h3>
            <p className="text-sm text-gray-500 font-mono mt-1">{submission.nomor_referensi}</p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
              </svg>
              Cetak Invoice
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-gray-200 transition-colors text-gray-500"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto bg-gray-100 p-4">
          <iframe
            srcDoc={invoiceHTML}
            title="Invoice"
            className="w-full h-[600px] border-0 rounded-lg shadow-sm"
            sandbox="allow-same-origin"
          />
        </div>
      </div>

      {/* Print iframe - hidden on screen, visible on print */}
      {showPrint && (
        <iframe
          srcDoc={invoiceHTML}
          title="Print Invoice"
          className="fixed inset-0 w-full h-full z-[100] hidden"
          onLoad={() => {
            setTimeout(() => {
              window.print();
              handleAfterPrint();
            }, 100);
          }}
        />
      )}
    </div>
  );
}
