-- Add complete warga identity fields
ALTER TABLE users ADD COLUMN IF NOT EXISTS no_kk VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS rt VARCHAR(3);
ALTER TABLE users ADD COLUMN IF NOT EXISTS rw VARCHAR(3);
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_keluarga VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS agama VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pekerjaan VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS pendidikan_terakhir VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_perkawinan VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_ayah VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS nama_ibu VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS kewarganegaraan VARCHAR(10) DEFAULT 'WNI';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
